inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Naming/PredicateName:
  Exclude:
    - 'test/test_helper.rb'
Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/sessions_helper.rb'
