require:
  - rubocop-rails

AllCops:
    NewCops: enable

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false
# ドキュメントの無いpublic classを許可する
Style/Documentation:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - 'test/test_helper.rb'

Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/sessions_helper.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
